<?php
$z[0]=Array("top","\r\n    <m:item name='模块管理' link='module_main.php' rank='sys_module' target='main' />\r\n    <m:item name='上传新模块' link='module_upload.php' rank='sys_module' target='main' />\r\n    <m:item name='模块生成向导' link='module_make.php' rank='sys_module' target='main' />\r\n    ",51,399);
$z[0][4]=array();
$z[0][4]['name']="模块管理";
$z[0][4]['c']="6,";
$z[0][4]['display']="block";
$z[1]=Array("top","\r\n  <m:item name='插件管理器' link='plus_main.php' rank='10' target='main' />\r\n  <m:item name='挑错管理' link='erraddsave.php' rank='plus_挑错管理' target='main' />\r\n<m:item name='百度新闻' link='baidunews.php' rank='plus_百度新闻' target='main' />\r\n<m:item name='文件管理器' link='file_manage_main.php' rank='plus_文件管理器' target='main' />\r\n<m:item name='广告管理' link='ad_main.php' rank='plus_广告管理' target='main' />\r\n<m:item name='友情链接' link='friendlink_main.php' rank='plus_友情链接模块' target='main' />\r\n<m:item name='投票模块' link='vote_main.php' rank='plus_投票模块' target='main' />\r\n\r\n",401,1125);
$z[1][4]=array();
$z[1][4]['item']="7";
$z[1][4]['name']="辅助插件";
$z[1][4]['display']="block";
$z[2]=Array("top","\r\n	          <m:item name='小说栏目管理' link='story_catalog.php' rank='story_catalog' target='main' />\r\n	          <m:item name='小说书目' link='story_books.php' rank='story_list' target='main' />\r\n	          <m:item name='小说连载内容' link='story_list_content.php' rank='story_list' target='main' />\r\n	          <m:item name='小说章节管理' link='story_list_chapter.php' rank='story_list' target='main' />\r\n	          <m:item name='更新小说HTML' link='makehtml_story.php' rank='sys_MakeHtml' target='main' />\r\n                  <m:item name='评论管理' link='story_feedback_main.php' rank='sys_MakeHtml' target='main' />\r\n	      ",1145,1871);
$z[2][4]=array();
$z[2][4]['name']="小说管理";
$z[2][4]['display']="block";
$z[2][4]['c']="6,";
$z[2][4]['rank']="";
$z[3]=Array("top","\r\n<m:item name='畅言模块' link='changyan_main.php' rank='sys_Feedback' target='main'/>\r\n<m:item name='评论管理' link='changyan_main.php?dopost=manage' rank='sys_Feedback' target='main'/>\r\n<m:item name='数据统计' link='changyan_main.php?dopost=stat' rank='sys_Feedback' target='main'/>\r\n<m:item name='导入导出' link='changyan_main.php?dopost=import' rank='sys_Feedback' target='main'/>\r\n<m:item name='畅言设置' link='changyan_main.php?dopost=setting' rank='sys_Feedback' target='main'/>\r\n",1873,2431);
$z[3][4]=array();
$z[3][4]['name']="畅言评论";
$z[3][4]['display']="block";
$z[4]=Array("top","\r\n<m:item name='德得模块' link='mda_main.php' rank='plus_广告管理' target='main'/>\r\n<m:item name='广告管理' link='mda_main.php?dopost=place' rank='plus_广告管理' target='main'/>\r\n<m:item name='查看报表' link='mda_main.php?dopost=report' rank='plus_广告管理' target='main'/>\r\n<m:item name='结算中心' link='mda_main.php?dopost=account' rank='plus_广告管理' target='main'/>\r\n<m:item name='德得设置' link='mda_main.php?dopost=setting' rank='plus_广告管理' target='main'/>\r\n",2437,2997);
$z[4][4]=array();
$z[4][4]['name']="德得广告";
$z[4][4]['display']="block";

?>